<?php
// ----------------------------------------------------------------------
// Registro elettronico scuole ospedaliere - tulip
// ----------------------------------------------------------------------
// LICENSE and CREDITS
// This program is free software and it's released under the terms of the
// GNU General Public License(GPL) Version 2 
// Link: http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
// Please READ carefully the Docs/License.txt file for further details
// Please READ the Docs/credits.txt file for complete credits list
// ----------------------------------------------------------------------
?>

<br /><br /><!--div align="center"><a href="<?=$up.".php"?>"><img src="immagini/menu.png" title="Men&ugrave; superiore" alt="Men&ugrave; superiore" border="0" /></a></div-->
 <br />
</div>
</body>
</html>
<?php $link->disconnect(); ?>
