<?php
// ----------------------------------------------------------------------
// Registro elettronico scuole ospedaliere - tulip
// ----------------------------------------------------------------------
// LICENSE and CREDITS
// This program is free software and it's released under the terms of the
// GNU General Public License(GPL) Version 2 
// Link: http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
// Please READ carefully the Docs/License.txt file for further details
// Please READ the Docs/credits.txt file for complete credits list
// ----------------------------------------------------------------------
// Nome file:  DefRuoli.inc
// Autore di questo file: Sophia Danesino 
// Puria Nafisi <puria@hipatia.info> 
// Descrizione: definizione costanti associate ai ruoli
// ----------------------------------------------------------------------
	

define("ID_ADMIN",1);
define("ID_OPERATORE",2);
define("ID_OSPEDALIERO",3);
define("ID_OSSERVATORE",4);
define("ID_AFFIDATARIO",5);
define("ID_DOMICILIARE",6);

?>
